### ISSUE TITLE
Suggestion For CommandLine Support

### ISSUE THREAD

**Issue by CrypticCus** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#1]
Hi can u add support for cmd? with or without 7zip installing support is fine. we can install 7zip silently anyway

7ziptc.exe 7zsetup.exe -toolbar "path" -filetype "path" -icons "path" -sfxicon "path" -7zfmgicon "path"

unattended and silently

**Comment by CrypticCus** [comment]
personally i only like 7ziptc and originally it was not created by you maybe thats why i like it. your gui's are too big and unnecessarly hard to use, i mean your other repacks. +abbodi and diakov is doing them for free for years and they are literally best since they can also tweaks the sources to strip from unnecessary things. no thanks i won't be supporting your project for a command line support i can do it myself.

**Comment by Wilenty** [comment]
I don't need your hate, also your money if you don't have them enough for your life...
When I closed my website in 2019 I shared full version of my VC++ repack for users from G3D, even for those who helped me with supportive words: https://forums.guru3d.com/threads/aio-runtime-libraries-by-wilenty-installer-uninstaller.418645/page-7
So, instead of ask me for the version of 7zTC with command-line support, you flow your anger on me, what a bad things did I for you?
Below I will show you what I did for money by myself (but I blurred some personal things of myself). And people didn't whine about my physical work - on the contrary, they were pleasantly surprised about the results. But in the internet any person/user can write what he want, even if they don't know situation of that people. Because I have problems with my back, I asked for the support, and when I had my own website and I shared all of my programs for free. But the amount of money was not enough to pay for next year for the website. So I had to make a tough decision to share my programs for free in hope that people will support me, or in demos and limited versions. Because previous method did not bring the desired results, I had to close my website, and I decided to share my programs in demos and limited versions. And it was not that my VC++ repack was unpopular on my website - it had big popularity but for free...
I don't have the time to explain for every single user/people on this world why I need the money of my work - in this same way as all of you needs them for our short life on this planet, so I will pin it.

"personally i only like 7ziptc and originally it was not created by you maybe thats why i like it."

I agree, InnoSetup has different GUI than other installers and 7zTM. But, you asked me on MDL to not change the default (B/W) colors, and I didn't change the default InnoSetup colors: https://forums.mydigitallife.net/threads/defender-switcher.84558/#post-1708518
So, I listen your request, I included your request in 7zTC, but then you are angry at me that I not shared the command-line support for free and you pointed me out all the things. You also don't get any income from the work you are doing?

"your gui's are too big and unnecessarly hard to use,"

Then ask InnoSetup owners to make it smaller and adapt it for your needs. I use InnoSetup with the size and design made by its owners.

"i mean your other repacks. +abbodi and diakov is doing them for free for years and they are literally best since they can also tweaks the sources to strip from unnecessary things. no thanks i won't be supporting your project for a command line support i can do it myself i suggested for your own good. not asked for it."

Abbodi won't support Windows XP fully in his VC++ repack from beginning until today, so, please don't compare me to his work: https://github.com/abbodi1406/vcredist/#overview
"Windows XP support is partial, the pack will install and detect the latest runtimes versions, but it will not check and remove non-compliant versions."
He is better in other things which I don't doing (for now). My repack of VC++ supports from Windows XP to 11, I even added the support for ARM64 architecture in my VC++ repack. Check yourself: https://github.com/Wilenty/VisualC-redist-installers-Demos
And about Diakov, he used my solution to create full-version of AskAdmin: https://diakov.net/14275-askadmin-v18.html
But he can't create repack of latest version of AskAdmin (v1.9), because I don't provided the solution "what needs to be changed" (I know what needs to be changed), even if my AutoIT Extractor works with all AutoIT based programs: https://github.com/Wilenty/Universal-AutoIT-Extractor-and-De-obfuscator
They working on something completely different, so, why you compare it and what you want to prove? Even sometimes they uses other works, but you don't want to see it at all...
Yes, you not asked for the command-line, but you also don't wanted to check the program description where is written about command-line support. So, that make you angry?

So, as you see some people doing some things better, but some things they doing worse. But we all live on this same "ball" named Earth, and we should help for each other if you like it or not.
Anyway, you don't know me, you don't know my financial situation, you don't know my health status, so, please don't judge me - I deserve for a bit of respect, even if you don't like my works.
And instead of focus on the work, you make me to think if I should answer to you. So it took some time...

---

All rooms made by me at the owners idea:

![DSC1](https://user-images.githubusercontent.com/61757638/175767687-be0b447a-03d2-4f1d-bd7b-639a61efc908.jpg)

![DSC2](https://user-images.githubusercontent.com/61757638/175767697-2ef6dff4-1afe-41a1-b669-e94cf592a029.jpg)

![DSC3](https://user-images.githubusercontent.com/61757638/175767703-6ee82644-ba78-475f-bfa9-9952dfdeaa7d.jpg)

![DSC4](https://user-images.githubusercontent.com/61757638/175767710-1abebe3d-c748-4f7c-adf5-c31bb25a792e.jpg)

![DSC5](https://user-images.githubusercontent.com/61757638/175767712-de11ba59-f45c-4f3b-8645-587b538ae294.JPG)

![DSC6](https://user-images.githubusercontent.com/61757638/175767715-556684d4-524c-4f03-9a98-8d0d2f021fc0.JPG)

![DSC7](https://user-images.githubusercontent.com/61757638/175767721-04ccbf6a-55cb-45bc-a2ae-2f1f595c1b89.jpg)

![DSC8](https://user-images.githubusercontent.com/61757638/175767737-b3573dfe-1739-4fbc-beaf-2024c198943a.jpg)

![DSC9](https://user-images.githubusercontent.com/61757638/175767740-a5aa4c49-f8e6-451d-b74d-58ddc44c7831.JPG)

![DSC10](https://user-images.githubusercontent.com/61757638/175767741-20124cf7-09a8-44b7-a4a4-abedeb15acf3.JPG)

![DSC11](https://user-images.githubusercontent.com/61757638/175767746-e0c4ea2a-e3a1-4baf-b3e7-00e04a0de1d5.jpg)

![DSC12](https://user-images.githubusercontent.com/61757638/175767751-c5142d30-c898-46b3-a5f4-93ec1ca9c2ac.jpg)

![DSC13](https://user-images.githubusercontent.com/61757638/175767753-66927796-1c3a-4860-a9a1-2f819aa02095.jpg)

![DSC14](https://user-images.githubusercontent.com/61757638/175767757-1355fbe6-1bf4-4923-8a96-2867ebd1dae4.jpg)

![DSC15](https://user-images.githubusercontent.com/61757638/175767760-51b7ad40-83bb-4622-b59d-d77de2e339b5.jpg)

![DSC16](https://user-images.githubusercontent.com/61757638/175767766-b7993656-2a61-4be2-8d7c-3c58e4254fba.jpg)

![DSC17](https://user-images.githubusercontent.com/61757638/175767984-997ed179-e7ed-46e1-b738-c079df07ccdb.JPG)

![DSC18](https://user-images.githubusercontent.com/61757638/175767771-03e47e31-8730-4630-ac81-f3b9bb1761b5.JPG)

Bathroom created based on 3D project, but owners of the house decided to use three lights instead of the fourths lights (comparing to the 3D project) on the front of the lowest part on the bathtub:
(you can check the project of the 3D Bathroom in the attached: 3DProjectOfBathroom.7z)

![DSC2](https://user-images.githubusercontent.com/61757638/175768028-24fa5673-da13-4f42-8caf-f792110c3c21.JPG)

![DSC3](https://user-images.githubusercontent.com/61757638/175768046-200c3170-9fed-433e-9cbd-8299cfed74b8.JPG)

![DSC4](https://user-images.githubusercontent.com/61757638/175768053-1eccf3b3-a531-4a6e-913a-2c9c470cf750.JPG)

![DSC5](https://user-images.githubusercontent.com/61757638/175768059-f21a2847-bc0b-4c0e-aecc-a2d136bc3b59.JPG)

![DSC6](https://user-images.githubusercontent.com/61757638/175768067-b55cc82e-6958-4990-bdc8-54f7d61258dc.JPG)

![DSC7](https://user-images.githubusercontent.com/61757638/175768072-0a82244b-c03c-4ea8-9a78-e7bc8997b50c.JPG)

![DSC8](https://user-images.githubusercontent.com/61757638/175768078-234b8987-22bc-4d5f-871f-4c4825575596.JPG)

![DSC9](https://user-images.githubusercontent.com/61757638/175768125-3a020666-3148-498d-8779-68ce3f4b0e9d.JPG)

![DSC10](https://user-images.githubusercontent.com/61757638/175768128-5d3219f7-f72f-4551-a971-3364b7256421.JPG)

Project pictures/screens: https://www22.zippyshare.com/v/K0ewHspd/file.html

Kitchen modernized based on the project:

![DSC1](https://user-images.githubusercontent.com/61757638/175768215-4c2f9cb0-0bca-4b07-aaed-e6520511fd0e.jpg)

![DSC2](https://user-images.githubusercontent.com/61757638/175768218-743ac6e7-b77d-4d0b-961c-c47f5a18fb8d.jpg)

![DSC3](https://user-images.githubusercontent.com/61757638/175768222-bb270c1f-00a2-494d-b3b7-0155ba4b9243.jpg)

![DSC4](https://user-images.githubusercontent.com/61757638/175768225-2b2c967a-91fb-4637-9551-5837e2ee9347.jpg)

![DSC5](https://user-images.githubusercontent.com/61757638/175768229-040324c0-7e5d-458f-9415-1661ee815d2e.jpg)

![DSC6](https://user-images.githubusercontent.com/61757638/175768230-46987a0b-93fc-4827-8d0b-58edf6008fbf.png)

![DSC7](https://user-images.githubusercontent.com/61757638/175768236-b7d29fbc-6edd-4316-85d1-258d32459132.jpg)

![DSC8](https://user-images.githubusercontent.com/61757638/175768238-1211fc0d-0f61-4796-b0cb-bde586b7ce54.jpg)

![DSC9](https://user-images.githubusercontent.com/61757638/175768242-419feac4-4e2b-450d-89a3-885e0057f757.jpg)

House upgraded from old style to the new one:

![DSC1](https://user-images.githubusercontent.com/61757638/175768265-47b581c7-1979-4f19-a070-eee1d9f7b637.jpg)

![DSC2](https://user-images.githubusercontent.com/61757638/175768271-c5f2cba7-8245-4e52-b476-52f60cea3808.jpg)

![DSC3](https://user-images.githubusercontent.com/61757638/175768274-7c09cee1-fc99-4c3e-8d45-8d8718b8b66a.jpg)

![DSC4](https://user-images.githubusercontent.com/61757638/175768278-1e8721e7-50a1-4075-910c-22d898fafed1.jpg)

![DSC5](https://user-images.githubusercontent.com/61757638/175768284-8856e8f3-6869-4195-9168-2c61b8e7c078.jpg)

![DSC6](https://user-images.githubusercontent.com/61757638/175768289-68b70a65-c3b9-4c92-be86-ebc9dd67d036.jpg)

![DSC7](https://user-images.githubusercontent.com/61757638/175768294-ff81b05f-17bd-4efb-84c3-d7a9f5d49847.jpg)

![DSC8](https://user-images.githubusercontent.com/61757638/175768297-21426754-1985-47b0-ab3a-106ad868e3c8.jpg)

![DSC9](https://user-images.githubusercontent.com/61757638/175768299-fd45fa12-1365-46d5-a828-642fbfef96f0.jpg)

![DSC10](https://user-images.githubusercontent.com/61757638/175768300-0a9f57df-31e3-4500-b0aa-566314c5509d.jpg)

![DSC11](https://user-images.githubusercontent.com/61757638/175768306-605e9038-3f37-449e-9c6a-04da882abbea.jpg)

![DSC12](https://user-images.githubusercontent.com/61757638/175768310-ccb451ed-826e-4b20-8836-c8bd75bc18ba.jpg)

![DSC13](https://user-images.githubusercontent.com/61757638/175768314-c6810e42-0b50-453f-ac00-716db56c4f4d.jpg)
