### ISSUE TITLE
program thinks 2 instances are running?

### ISSUE THREAD

**Issue by smcxx88** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#11]
will only install icons and some times doesn't install at all because it says theres 2 of the same programs open, both happens on win 10&11

**Comment by Wilenty** [comment]
Hello @smcxx88.
(at the outset) You don't think you should write some text in the issue, instead of writing the issue thread only?
![No description provided](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/c538bde7-5582-49c8-bf7e-8b6f5bcec48e)


I will answer to your questions (included in the topic) in reverse order.
```some times doesn't install at all because it says theres 2 of the same programs open, both happens on win 10&11```
Fix: https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/releases/tag/v3.01

```will only install icons```
![298281870-5c211b98-3321-4a7a-8de6-4f429a90f99a](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/daa9f58f-e23c-4b5b-934c-199e473cb0a6)
but, when adding NanaZip.dll to 7-zip installation, only the file-type is available, because it's required. (Issue number 10)

Greetings,
Wilenty

**Comment by smcxx88** [comment]
> Owner

sorry buddy my bad lol i've fixed that
