### ISSUE TITLE
Apply FileType, ToolBar, Icons at once in cli

### ISSUE THREAD

**Issue by assiless** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#17]
v3.0+ add FileType, ToolBar, Icons at same time in gui ❌ not-supported

v2.5 add FileType, ToolBar, Icons at same time in gui ✔ supported

i can go back to 2.5 but i'm intersted in 3.2 which support cli
```pwsh
./7zTC.cmd /lang=english /SevenZip-Path="${HOME}\scoop\apps\7zip\current" /Apply-FileType="Windows 10 Default" /Apply-ToolBar="Windows 10 Default" /Apply-Icons="7-Zip Original Theme" 
```
the only workaround is this
```pwsh
./7zTC.cmd /lang=english /SevenZip-Path="${HOME}\scoop\apps\7zip\current" /Apply-FileType="Windows 10 Default"
./7zTC.cmd /lang=english /SevenZip-Path="${HOME}\scoop\apps\7zip\current" /Apply-ToolBar="Windows 10 Default"
./7zTC.cmd /lang=english /SevenZip-Path="${HOME}\scoop\apps\7zip\current" /Apply-Icons="7-Zip Original Theme"
```

v3.2 seem to apply one at time in gui and cli

**Comment by Wilenty** [comment]
Hello @assiless.

All versions of 7zTC from v3 allows: one theme at one execution. Look at the main program page and read third line of the text (i won't screenshot it and paste it over and over again). So first start reading, and then think about writing.

I've spend more hours on creating 7zTC and testing it with different versions of 7-zip and NanaZip than most of users on using it. So, can I expect gratitude from people who use my works?

I didn't think adding the command-line would change anything in my financial situation, but I had informed all of the users in a clear state that I need your help. But instead of helping me people like you comes here and writing messages with a "workaround".

Greetings,
Wilenty

**Comment by Wilenty** [comment]
Looking at cmd (batch) files does not exempt you from reading the program description.

The "7zTC [7-Zip].cmd" file is a copy from the full version of the program, so...

But, did you checked the "7zTC [Launch].cmd" before extraction? If not then I will show you few first lines:
```bat
@echo off
rem -> Yours settings are here:

set IconsTheme=NanaZip Original Theme
:: OR
set FileTypeTheme=Greg's Icons
:: OR
set "ToolBarTheme=Black & White"
```

> i think from this snippet from your main program "7zTC [7-Zip].cmd" allow Apply FileType, ToolBar and Icons **at one execution**

No, you "started reading the book from the back side". All of these parameters need to be written there if the user wants to choose one of the three different types of themes. So please stop this endless discussion about what you want to see and what you don't want to see.

Greetings,
Wilenty
