### ISSUE TITLE
Annoying Development Decision

### ISSUE THREAD

**Issue by Kyzoku** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#18]
You have made this app a colossal annoyance with your development decisions.

Forcing a user to run your app over and over again to set the themes is ridiculous, unless there is a legitimate limitation preventing it.
Asking a user if they want to visit your support page and then making the application do nothing if the answer is no is pointless. No one wants to open your support page 3 times in a row to completely theme the app.

My suggestion is that if you want to add an artificial limitation to your software then add a license system for those who support you and when used allows the full capabilities of the theme application.  In the current state, even if a user supports you the software is still ridiculously limited for them, and they still get nagged to go to your support page every time they use it.

Another suggestion is your nag screen to visit shouldn't be a yes or no option.  Either just open your support page without a nag or tell the user that choosing no results in the software not functioning.

You don't need to respond to this or even make any changes as I don't really care. I won't bother reading it if you do because you have a bad habit of being a childish twat to your users when they don't quite understand how your janky software functions.

Perhaps I'll check in some day and see your software in a good state and decide to support then, but until then. Nah

**Comment by Wilenty** [comment]
Hello @Kyzoku.

For first look at the first issue: "Suggestion For CommandLine Support".

Also, "jump" over other issues and check how many times I asked for support, and it changed exactly nothing.

I still got more money from repairing computers than from the apps I have created. My apps are fine for free, but most people don't want to pay for it.
So don't write nice fairy tales here that you will support me if I change this or that.
You could have done that before you started insulting me and my work here.

In general users wants to add this or that but they don't want to buy a simple coffee for the developer of whom the app they are using. So, I had no choice to inform users in any other way...

I won't add any "license system", because I am small developer and I have no income from it, so I don't invest my hard-earned money for it.

If opening my support page three times is not enough I can do a loot more (joke). :D

I propose to you don't use a "janky software" and don't waste our time for such discussions.

Greetings,
Wilenty
