### ISSUE TITLE
Some Icons Don't Change

### ISSUE THREAD

**Issue by JAK0723** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#4]
OS: Windows 11 Home, Version 22H2, build 22621.674
7-Zip Version: 22.01

I was able to correctly apply a toolbar theme, however when changing the filetype icons, some of them will not be applied. Specifically, the 7z, CAB, ISO, TAR, and ZIP icons. I've tried multiple different themes, including the default, but they all fail to change these filetype icons.

Here is the [log file](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/files/9791498/7zTC.Apply.-.windows.11.txt), I've also attached a screenshot showing the problem.

![explorer_2022-10-15_18-54-09](https://user-images.githubusercontent.com/29014804/195975973-e74361dc-133c-468a-8f0f-a9049c407cb5.png)

**Comment by Wilenty** [comment]
Hello,
please look at the first line in the log file (last line in the log, because it's reversed):
```
[...] On Windows 11 the icons may not be refreshed without OS restart!
[...] Rebuilding icons cache...
```

That's the problem with W11...

**Comment by JAK0723** [comment]
I have restarted my computer, but the icons have not changed.

**Comment by Wilenty** [comment]
Okay, let me check the log-file line-by-line...

**Comment by Wilenty** [comment]
Sorry, but I don't see anything strange, or abnormal, in the log file...

Update results of:
7z.ico) log-line: 1066
```
[18:48:11,526] Successfully updated resource "0" of file "(...)\Windows 11\7z.ico". (OK)
```
CAB.ico) log-line: 800
```
[18:48:11,634] Successfully updated resource "7" of file "(...)\Windows 11\cab.ico". (OK)
```
ISO.ico) log-line: 762
```
[18:48:11,650] Successfully updated resource "8" of file "(...)\Windows 11\iso.ico". (OK)
```
TAR.ico) log-line: 572
```
[18:48:11,725] Successfully updated resource "13" of file "(...)\Windows 11\tar.ico". (OK)
```
ZIP.ico) log-line: 1028
```
[18:48:11,542] Successfully updated resource "1" of file "(...)\Windows 11\zip.ico". (OK)
```

So, maybe you will send me the updated 7z.dll file, or you can check the updated icons in the ResourceHacker: http://angusj.com/resourcehacker/ in the "Group Icon".

**Comment by JAK0723** [comment]
OK, I've attached the 7z.dll file. I had to zip it, since GitHub doesn't seem to allow uploading DLL files in comments.

[7z.zip](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/files/9791634/7z.zip)

**Comment by Wilenty** [comment]
As I thought, they where changed correctly:
![unknown](https://user-images.githubusercontent.com/61757638/195978265-a660bbec-f621-4e98-9c15-caa920f8b9e7.png)

So, you have to clear the icon-cache, because M$ changing the ways from release to release (and we can't get all the changes they did)...

Please try one of:
1) https://www.elevenforum.com/t/rebuild-icon-cache-in-windows-11.2049/
```
ie4uinit.exe -show
```
2) https://appuals.com/rebuild-icon-cache-windows-11/
```
cd /d %userprofile%\AppData\Local\Microsoft\Windows\Explorer
attrib –h iconcache_*.db
del iconcache_*.db start explorer
```

Maybe you will have to kill the "explorer.exe" in the task-manager, if so, please leave the task-manager it running and reboot the computer from the task-manager (because new version of "explorer.exe" in Windows 11 holding the icons-cache files).

And please let me know.

**Comment by JAK0723** [comment]
Neither of them appear to have worked. I did confirm that the iconcache files were deleted by checking with ls, but those same filetypes still the wrong icons.

Also, I had to change the `–` to a `-` in the `attrib –h iconcache_*.db` command.

**Comment by Wilenty** [comment]
So, now I don't know how I can help you with that. Files were changed correctly, but the "explorer.exe" (Windows 11) still shows old icons. Maybe you will have to download the ResourceHacer and check the icons yourself? The "Icon Group" names you see in the previous message with quote of the log-file. Or, maybe you will have to open the task-manager, kill the "explorer.exe", clear cache and reboot the OS from the task-manager.

Now you know, why people won't use it (Windows 11) on work computers, because things that worked, works wrong, or won't work at all...

**Comment by JAK0723** [comment]
I did kill explorer.exe before deleting the iconcache files. Though I had to use the `shutdown -r` command in the terminal, since it appears you can no longer restart the computer from the new task manager.

As you suggested, I checked the DLL with ResourceHacker and the icons all look correct as shown in the attached screenshot. I suppose this is some issue with Windows 11, as you mentioned. Oddly, this program did correctly change the filetype icons my Windows 11 desktop PC, it just doesn't work on my new Windows 11 laptop.

![ResourceHacker_2022-10-15_20-48-17](https://user-images.githubusercontent.com/29014804/195980273-ca2b1d0e-97d4-4582-8611-c2a0733e443e.png)

**Comment by Wilenty** [comment]
My program tries to delete these icons-cache files on Windows 10/11, but not killing the "explorer.exe" to not scary the user...

For sure it's a problem with Windows 11, and you should report it on their forum (that they know it).
Also, if you want, you can re-install the Windows from scratch, but I don't know if it won't break the warranty (of the new laptop), and if it helps.

I pin this issue to prevent future questions about this same problem. So, you can delete the log-file from first message (if you want).

**Comment by DeCoded-Void** [comment]
I had the same issue and I was able to fix it on Windows 11. 

I used FileTypesMan to view the location of the icons that explorer was referencing and to see if the MIME types of the file are accurate. 

In my case it was pointing to icons located in `C:\Program Files\7-Zip\Icons` 

Manually replacing the icon files in that directory and restarting windows explorer fixed it for me however I could also fix it by editing the icon location in the program I just mentioned.

**Comment by Wilenty** [comment]
Hello @DeCoded-Void,
sorry for late reply.

I don't change any associations for 7-ZIP. I only adding the icon associations for NanaZip on the installation stage, because they are missing.

Can I ask how you installed the 7-ZIP, i.e. via my program, or via original installer?

Also, can you check the icons associations before using my program, and after it?

I realize that people like the "fresh view" in Windows 11, but (unfortunately) the Windows 11 is still in the testing stage, so I don't use it.

I tested my program on Windows XP with 7-ZIP, because NanaZip does not work on XP, and on Windows 7/10 with 7-ZIP/NanaZip.

Greetings,
Wilenty

**Comment by Wilenty** [comment]
By the way.

If you will view any of the original 7-ZIP installers:
https://7-zip.org/a/7z2201-x64.exe
https://7-zip.org/a/7z2201.exe
https://7-zip.org/a/7z2201-arm64.exe
( also mine repacks: https://github.com/Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script )
you will not see the folder "icons" inside it, so, I don't know from where it comes on Windows 11...

**Comment by DeCoded-Void** [comment]
I downloaded it using the original installer, specifically the 64-bit version from 7-zip.org while I was in Windows 10 and I used the original 7zTM. I upgraded to Windows 11 sometime earlier this year or last year.

I reused the program with a new icon pack since the aesthetic was clashing with windows 11 icons, but with no success, so I went browsing and found this repository and had no luck from that either. 

A screenshot of the dll file from Resource Hacker and FileTypesMan:
![Screenshot 2022-12-27 005319](https://user-images.githubusercontent.com/11778439/209618163-14db6cd7-1923-4e99-82df-3a5b079ad542.png)

A thing to note is that even though the dll file was changed, I still had to point to the directory the icon is in or replace the referenced icon.

**Comment by Wilenty** [comment]
> A thing to note is that even though the dll file was changed, I still had to point to the directory the icon is in or replace the referenced icon.

I can find and fix the icons associations in the OS registry, but I don't know if it's a good idea. Also I can copy the icon files to that "(...)\icons" folder, but then you will have the icons twice (in that DLL file and separately in the "(...)\icons" folder), if the "(...)\icons" directory exists (because I don't know if it's a Windows 11 bug or feature).

Can you help me out how to solve this problem? Because i really have no idea why it does not work only on Windows 11, but works without any problem on all other OS's.

**Comment by Wilenty** [comment]
Hello all.
Probably I have found simple as possible solution to solve the problem with icons associations in Windows 11.

For first open the 7-ZIP program, and click in the top menu: Tools -> Options
(*if you want to change the icons associations for all users - execute 7-ZIP File Manager with Admin Rights)

If you don't had any program installed that can manage the compression icons associations, then you will see something like this:
![01](https://user-images.githubusercontent.com/61757638/209952154-87e994e7-65f9-4e1a-83af-6cbb0becb925.jpg)

If you want to change all icons for 7-ZIP for yourself, just click the left plus (+) above the list of the icons until you will see 7-ZIP in the first column, and click Apply / OK.
![03](https://user-images.githubusercontent.com/61757638/209952221-25c5aa03-f434-49db-9198-1c1d88f0fc9c.jpg)

If you want to change all icons for 7-ZIP for all users*, 
just click the right plus (+) above the list of the icons until you will see 7ZIP in the second column, and click Apply / OK.
![04](https://user-images.githubusercontent.com/61757638/209952291-928d5d59-5dec-4507-b5ae-56a062fbfdf6.jpg)

If you want to change single icon for 7-ZIP for yourself (I used rar in below screenshot) click on the middle column in the rar line until you will see 7-ZIP in the middle column, and click Apply / OK.
![06](https://user-images.githubusercontent.com/61757638/209952353-833d3eff-4f61-4731-a256-ffb4bec041c0.jpg)

If you want to change single icon for 7-ZIP for all users* (I used rar in below screenshot) click on the right column in the rar line until you will see 7-ZIP in the right column, and click Apply / OK.
![07](https://user-images.githubusercontent.com/61757638/209952405-2a5b4c8b-8c91-4f7d-bab5-4c587ad269dc.jpg)

By the way, if this same problem with icons associations will happens to NanaZip, please re-install or update the NanaZip, because only the installation adds the icons associations for NanaZip.

Happy New Year!

**Comment by Wilenty** [comment]
Hello all.
Probably I have found simple as possible solution to solve the problem with icons associations in Windows 11.

For first open the 7-ZIP program, and click in the top menu: Tools -> Options
(*if you want to change the icons associations for all users - execute 7-ZIP File Manager with Admin Rights)

If you don't had any program installed that can manage the compression icons associations, then you will see something like this:
![01](https://user-images.githubusercontent.com/61757638/209956234-3eb86109-7446-4b48-93ee-431908c2d341.jpg)

If you want to change all icons for 7-ZIP for yourself, just click the left plus (+) above the list of the icons until you will see 7-ZIP in the first column, and click Apply / OK.
![03](https://user-images.githubusercontent.com/61757638/209956346-9e6378fc-f3ad-4a8e-a947-8cad6755cb2e.jpg)

If you want to change all icons for 7-ZIP for all users*, just click the right plus (+) above the list of the icons until you will see 7ZIP in the second column, and click Apply / OK.
![04](https://user-images.githubusercontent.com/61757638/209956494-59afa45b-009e-4962-bdb7-39f998cbc418.jpg)

If you want to change single icon for 7-ZIP for yourself (I used rar in below screenshot) click on the middle column in the rar line until you will see 7-ZIP in the middle column, and click Apply / OK.
![06](https://user-images.githubusercontent.com/61757638/209956602-160adb22-22e2-4e74-888c-7ab16f11c6e2.jpg)

If you want to change single icon for 7-ZIP for all users* (I used rar in below screenshot) click on the right column in the rar line until you will see 7-ZIP in the right column, and click Apply / OK.
![07](https://user-images.githubusercontent.com/61757638/209956729-d17aa0d8-8f8e-439b-af41-562994d67716.jpg)

By the way, if this same problem with icons associations will happens to NanaZip, please re-install or update the NanaZip, because only the installation adds the icons associations for NanaZip.

Happy New Year!

**Comment by DeCoded-Void** [comment]
I can confirm this on my Windows 11 PC, changing the association from that menu worked with changing individual icons.

**Comment by Wilenty** [comment]
Thank you for the confirmation @DeCoded-Void. :)

**Comment by JAK0723** [comment]
Sorry for the late response, I haven't had much of a reason to use my laptop until recently.

I can confirm that changing the file associations did fix the icons, somewhat. Though changing the associations through 7-ZIP didn't work properly. Instead, I had to change the default program for the different file types to 7-ZIP though Windows' "open-with" > "always" dialog.

**Comment by NSExceptional** [comment]
Apologies for bumping an old issue, but I just wanted to say that deleting all the `iconcache_*` files in `%userprofile%\AppData\Local\Microsoft\Windows\Explorer` did the trick for me. I'm on Windows 10.

**Comment by Wilenty** [comment]
Hello @NSExceptional.

You have no apologize for, if your comment helps at least one person it will be great!
My script tries to delete these files on W10 & W11, but maybe M$ Defender, or anything else blocks it - have no idea.
Users don't like to read descriptions these days, but most of them spend more and more time on social media...

Greetings,
Wilenty
